version: "3.8"

networks:
  laravel:
    driver: ${NETWORKS_DRIVER}
        
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  mssql:
    driver: ${VOLUMES_DRIVER}
  memcached:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:

  # PHP Service
  php:
    build:
      context: ./php
      target: php
      args:
        - APP_ENV=${APP_ENV}
        - PHP_VERSION=${PHP_VERSION}
        - PHP_INSTALL_BCMATH=${PHP_INSTALL_BCMATH}
        - PHP_INSTALL_MYSQLI=${PHP_INSTALL_MYSQLI}
        - PHP_INSTALL_INTL=${PHP_INSTALL_INTL}
        - PHP_INSTALL_IMAGEMAGICK=${PHP_INSTALL_IMAGEMAGICK}
        - PHP_IMAGEMAGICK_VERSION=${PHP_IMAGEMAGICK_VERSION}
        - PHP_INSTALL_OPCACHE=${PHP_INSTALL_OPCACHE}
        - PHP_INSTALL_IMAGE_OPTIMIZERS=${PHP_INSTALL_IMAGE_OPTIMIZERS}
        - PHP_INSTALL_PHPREDIS=${PHP_INSTALL_PHPREDIS}
        - PHP_INSTALL_MEMCACHED=${PHP_INSTALL_MEMCACHED}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 9000
    depends_on:
      - mysql
    networks:
      - laravel

  # MYSQL Service
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    evironment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    networks:
      - laravel

  # NGINX Service
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    restart: unless-stopped
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    depens_on:
      - php
    networks:
      - laravel

  # REDIS Service
  redis:
    buid: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - ${REDIS_PORT}:6379
    newtorks:
      - laravel